logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-oep-integrator
  security:
    oauth2:
      client:
        registration:
          party:
            authorization-grant-type: client_credentials
            provider: party
logbook:
  body-filters:
    x-path:
      - key: '//EncodedData[string-length(text()) > 0]'
        value: '[base64]'
