#========================================
# Test profile settings (IT tests)
#========================================
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          party:
            client-id: someClientId
            client-secret: someClientSecret
        provider:
          party:
            token-uri: http://localhost:${wiremock.server.port}/api-token
integration:
  party:
    url: http://localhost:${wiremock.server.port}/api-party
properties:
  credentials:
    secret-key: "WbVG8XC%m&9Z!7a$xyKGWzB^#kUSoUUs"
