#========================================
# Test profile settings (junit tests)
#========================================
logging:
  level:
    root: DEBUG
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
properties:
  credentials:
    secret-key: "WbVG8XC%m&9Z!7a$xyKGWzB^#kUSoUUs"
